### ISSUE TITLE
isTtySupported gives fatal error on when symfony/process is not v4 

### ISSUE THREAD

**Issue by siegerhansma** [statamic/cli#14]
`PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\Process::isTtySupported() in /Users/siegerhansma/.composer/vendor/statamic/cli/src/Please.php:35
`

I already have version 3.4 installed so I'm getting a fatal error when I'm trying to run make:user.

**Comment by ericrowan** [comment]
Confirming the same error as @siegerhansma

**Comment by Fleroviumizer** [comment]
I encountered the same error

**Comment by dstollie** [comment]
For some reason this only happens when I run it locally on my Host machine (mac). When I'm running this inside the guest machine (ubuntu vagrant) the cli tool works perfect

**Comment by jasonvarga** [comment]
Thanks for the reports, everyone. We'll have the fix soon.

@dstollie You probably have symfony/process 3.4 on your host and 4.0 on your guest.

**Comment by jasonvarga** [comment]
Should be fixed in 1.0.5
