### ISSUE TITLE
composer install fails

### ISSUE THREAD

**Issue by ibdf** [statamic/cli#2]
cmd: composer global require statamic/cli
result:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for statamic/cli ^1.0 -> satisfiable by statamic/cli[1.0].
    - Conclusion: remove symfony/console v4.0.1
    - Conclusion: don't install symfony/console v4.0.1
    - statamic/cli 1.0 requires symfony/console ~2.3|~3.0 -> satisfiable by symfony/console[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1].
    - Can only install one of: symfony/console[v3.0.0, v4.0.1].
    - Can only install one of: symfony/console[v3.0.1, v4.0.1].
    - Can only install one of: symfony/console[v3.0.2, v4.0.1].
    - Can only install one of: symfony/console[v3.0.3, v4.0.1].
    - Can only install one of: symfony/console[v3.0.4, v4.0.1].
    - Can only install one of: symfony/console[v3.0.5, v4.0.1].
    - Can only install one of: symfony/console[v3.0.6, v4.0.1].
    - Can only install one of: symfony/console[v3.0.7, v4.0.1].
    - Can only install one of: symfony/console[v3.0.8, v4.0.1].
    - Can only install one of: symfony/console[v3.0.9, v4.0.1].
    - Can only install one of: symfony/console[v3.1.0, v4.0.1].
    - Can only install one of: symfony/console[v3.1.1, v4.0.1].
    - Can only install one of: symfony/console[v3.1.10, v4.0.1].
    - Can only install one of: symfony/console[v3.1.2, v4.0.1].
    - Can only install one of: symfony/console[v3.1.3, v4.0.1].
    - Can only install one of: symfony/console[v3.1.4, v4.0.1].
    - Can only install one of: symfony/console[v3.1.5, v4.0.1].
    - Can only install one of: symfony/console[v3.1.6, v4.0.1].
    - Can only install one of: symfony/console[v3.1.7, v4.0.1].
    - Can only install one of: symfony/console[v3.1.8, v4.0.1].
    - Can only install one of: symfony/console[v3.1.9, v4.0.1].
    - Can only install one of: symfony/console[v3.2.0, v4.0.1].
    - Can only install one of: symfony/console[v3.2.1, v4.0.1].
    - Can only install one of: symfony/console[v3.2.10, v4.0.1].
    - Can only install one of: symfony/console[v3.2.11, v4.0.1].
    - Can only install one of: symfony/console[v3.2.12, v4.0.1].
    - Can only install one of: symfony/console[v3.2.13, v4.0.1].
    - Can only install one of: symfony/console[v3.2.14, v4.0.1].
    - Can only install one of: symfony/console[v3.2.2, v4.0.1].
    - Can only install one of: symfony/console[v3.2.3, v4.0.1].
    - Can only install one of: symfony/console[v3.2.4, v4.0.1].
    - Can only install one of: symfony/console[v3.2.5, v4.0.1].
    - Can only install one of: symfony/console[v3.2.6, v4.0.1].
    - Can only install one of: symfony/console[v3.2.7, v4.0.1].
    - Can only install one of: symfony/console[v3.2.8, v4.0.1].
    - Can only install one of: symfony/console[v3.2.9, v4.0.1].
    - Can only install one of: symfony/console[v3.3.0, v4.0.1].
    - Can only install one of: symfony/console[v3.3.1, v4.0.1].
    - Can only install one of: symfony/console[v3.3.10, v4.0.1].
    - Can only install one of: symfony/console[v3.3.11, v4.0.1].
    - Can only install one of: symfony/console[v3.3.12, v4.0.1].
    - Can only install one of: symfony/console[v3.3.13, v4.0.1].
    - Can only install one of: symfony/console[v3.3.14, v4.0.1].
    - Can only install one of: symfony/console[v3.3.2, v4.0.1].
    - Can only install one of: symfony/console[v3.3.3, v4.0.1].
    - Can only install one of: symfony/console[v3.3.4, v4.0.1].
    - Can only install one of: symfony/console[v3.3.5, v4.0.1].
    - Can only install one of: symfony/console[v3.3.6, v4.0.1].
    - Can only install one of: symfony/console[v3.3.7, v4.0.1].
    - Can only install one of: symfony/console[v3.3.8, v4.0.1].
    - Can only install one of: symfony/console[v3.3.9, v4.0.1].
    - Can only install one of: symfony/console[v3.4.0, v4.0.1].
    - Can only install one of: symfony/console[v3.4.1, v4.0.1].
    - Can only install one of: symfony/console[v2.3.0, v4.0.1].
    - Can only install one of: symfony/console[v2.3.1, v4.0.1].
    - Can only install one of: symfony/console[v2.3.10, v4.0.1].
    - Can only install one of: symfony/console[v2.3.11, v4.0.1].
    - Can only install one of: symfony/console[v2.3.12, v4.0.1].
    - Can only install one of: symfony/console[v2.3.13, v4.0.1].
    - Can only install one of: symfony/console[v2.3.14, v4.0.1].
    - Can only install one of: symfony/console[v2.3.15, v4.0.1].
    - Can only install one of: symfony/console[v2.3.16, v4.0.1].
    - Can only install one of: symfony/console[v2.3.17, v4.0.1].
    - Can only install one of: symfony/console[v2.3.18, v4.0.1].
    - Can only install one of: symfony/console[v2.3.19, v4.0.1].
    - Can only install one of: symfony/console[v2.3.2, v4.0.1].
    - Can only install one of: symfony/console[v2.3.20, v4.0.1].
    - Can only install one of: symfony/console[v2.3.21, v4.0.1].
    - Can only install one of: symfony/console[v2.3.22, v4.0.1].
    - Can only install one of: symfony/console[v2.3.23, v4.0.1].
    - Can only install one of: symfony/console[v2.3.24, v4.0.1].
    - Can only install one of: symfony/console[v2.3.25, v4.0.1].
    - Can only install one of: symfony/console[v2.3.26, v4.0.1].
    - Can only install one of: symfony/console[v2.3.27, v4.0.1].
    - Can only install one of: symfony/console[v2.3.28, v4.0.1].
    - Can only install one of: symfony/console[v2.3.29, v4.0.1].
    - Can only install one of: symfony/console[v2.3.3, v4.0.1].
    - Can only install one of: symfony/console[v2.3.30, v4.0.1].
    - Can only install one of: symfony/console[v2.3.31, v4.0.1].
    - Can only install one of: symfony/console[v2.3.32, v4.0.1].
    - Can only install one of: symfony/console[v2.3.33, v4.0.1].
    - Can only install one of: symfony/console[v2.3.34, v4.0.1].
    - Can only install one of: symfony/console[v2.3.35, v4.0.1].
    - Can only install one of: symfony/console[v2.3.36, v4.0.1].
    - Can only install one of: symfony/console[v2.3.37, v4.0.1].
    - Can only install one of: symfony/console[v2.3.38, v4.0.1].
    - Can only install one of: symfony/console[v2.3.39, v4.0.1].
    - Can only install one of: symfony/console[v2.3.4, v4.0.1].
    - Can only install one of: symfony/console[v2.3.40, v4.0.1].
    - Can only install one of: symfony/console[v2.3.41, v4.0.1].
    - Can only install one of: symfony/console[v2.3.42, v4.0.1].
    - Can only install one of: symfony/console[v2.3.5, v4.0.1].
    - Can only install one of: symfony/console[v2.3.6, v4.0.1].
    - Can only install one of: symfony/console[v2.3.7, v4.0.1].
    - Can only install one of: symfony/console[v2.3.8, v4.0.1].
    - Can only install one of: symfony/console[v2.3.9, v4.0.1].
    - Can only install one of: symfony/console[v2.4.0, v4.0.1].
    - Can only install one of: symfony/console[v2.4.1, v4.0.1].
    - Can only install one of: symfony/console[v2.4.10, v4.0.1].
    - Can only install one of: symfony/console[v2.4.2, v4.0.1].
    - Can only install one of: symfony/console[v2.4.3, v4.0.1].
    - Can only install one of: symfony/console[v2.4.4, v4.0.1].
    - Can only install one of: symfony/console[v2.4.5, v4.0.1].
    - Can only install one of: symfony/console[v2.4.6, v4.0.1].
    - Can only install one of: symfony/console[v2.4.7, v4.0.1].
    - Can only install one of: symfony/console[v2.4.8, v4.0.1].
    - Can only install one of: symfony/console[v2.4.9, v4.0.1].
    - Can only install one of: symfony/console[v2.5.0, v4.0.1].
    - Can only install one of: symfony/console[v2.5.1, v4.0.1].
    - Can only install one of: symfony/console[v2.5.10, v4.0.1].
    - Can only install one of: symfony/console[v2.5.11, v4.0.1].
    - Can only install one of: symfony/console[v2.5.12, v4.0.1].
    - Can only install one of: symfony/console[v2.5.2, v4.0.1].
    - Can only install one of: symfony/console[v2.5.3, v4.0.1].
    - Can only install one of: symfony/console[v2.5.4, v4.0.1].
    - Can only install one of: symfony/console[v2.5.5, v4.0.1].
    - Can only install one of: symfony/console[v2.5.6, v4.0.1].
    - Can only install one of: symfony/console[v2.5.7, v4.0.1].
    - Can only install one of: symfony/console[v2.5.8, v4.0.1].
    - Can only install one of: symfony/console[v2.5.9, v4.0.1].
    - Can only install one of: symfony/console[v2.6.0, v4.0.1].
    - Can only install one of: symfony/console[v2.6.1, v4.0.1].
    - Can only install one of: symfony/console[v2.6.10, v4.0.1].
    - Can only install one of: symfony/console[v2.6.11, v4.0.1].
    - Can only install one of: symfony/console[v2.6.12, v4.0.1].
    - Can only install one of: symfony/console[v2.6.13, v4.0.1].
    - Can only install one of: symfony/console[v2.6.2, v4.0.1].
    - Can only install one of: symfony/console[v2.6.3, v4.0.1].
    - Can only install one of: symfony/console[v2.6.4, v4.0.1].
    - Can only install one of: symfony/console[v2.6.5, v4.0.1].
    - Can only install one of: symfony/console[v2.6.6, v4.0.1].
    - Can only install one of: symfony/console[v2.6.7, v4.0.1].
    - Can only install one of: symfony/console[v2.6.8, v4.0.1].
    - Can only install one of: symfony/console[v2.6.9, v4.0.1].
    - Can only install one of: symfony/console[v2.7.0, v4.0.1].
    - Can only install one of: symfony/console[v2.7.1, v4.0.1].
    - Can only install one of: symfony/console[v2.7.10, v4.0.1].
    - Can only install one of: symfony/console[v2.7.11, v4.0.1].
    - Can only install one of: symfony/console[v2.7.12, v4.0.1].
    - Can only install one of: symfony/console[v2.7.13, v4.0.1].
    - Can only install one of: symfony/console[v2.7.14, v4.0.1].
    - Can only install one of: symfony/console[v2.7.15, v4.0.1].
    - Can only install one of: symfony/console[v2.7.16, v4.0.1].
    - Can only install one of: symfony/console[v2.7.17, v4.0.1].
    - Can only install one of: symfony/console[v2.7.18, v4.0.1].
    - Can only install one of: symfony/console[v2.7.19, v4.0.1].
    - Can only install one of: symfony/console[v2.7.2, v4.0.1].
    - Can only install one of: symfony/console[v2.7.20, v4.0.1].
    - Can only install one of: symfony/console[v2.7.21, v4.0.1].
    - Can only install one of: symfony/console[v2.7.22, v4.0.1].
    - Can only install one of: symfony/console[v2.7.23, v4.0.1].
    - Can only install one of: symfony/console[v2.7.24, v4.0.1].
    - Can only install one of: symfony/console[v2.7.25, v4.0.1].
    - Can only install one of: symfony/console[v2.7.26, v4.0.1].
    - Can only install one of: symfony/console[v2.7.27, v4.0.1].
    - Can only install one of: symfony/console[v2.7.28, v4.0.1].
    - Can only install one of: symfony/console[v2.7.29, v4.0.1].
    - Can only install one of: symfony/console[v2.7.3, v4.0.1].
    - Can only install one of: symfony/console[v2.7.30, v4.0.1].
    - Can only install one of: symfony/console[v2.7.31, v4.0.1].
    - Can only install one of: symfony/console[v2.7.32, v4.0.1].
    - Can only install one of: symfony/console[v2.7.33, v4.0.1].
    - Can only install one of: symfony/console[v2.7.34, v4.0.1].
    - Can only install one of: symfony/console[v2.7.35, v4.0.1].
    - Can only install one of: symfony/console[v2.7.36, v4.0.1].
    - Can only install one of: symfony/console[v2.7.37, v4.0.1].
    - Can only install one of: symfony/console[v2.7.38, v4.0.1].
    - Can only install one of: symfony/console[v2.7.39, v4.0.1].
    - Can only install one of: symfony/console[v2.7.4, v4.0.1].
    - Can only install one of: symfony/console[v2.7.5, v4.0.1].
    - Can only install one of: symfony/console[v2.7.6, v4.0.1].
    - Can only install one of: symfony/console[v2.7.7, v4.0.1].
    - Can only install one of: symfony/console[v2.7.8, v4.0.1].
    - Can only install one of: symfony/console[v2.7.9, v4.0.1].
    - Can only install one of: symfony/console[v2.8.0, v4.0.1].
    - Can only install one of: symfony/console[v2.8.1, v4.0.1].
    - Can only install one of: symfony/console[v2.8.10, v4.0.1].
    - Can only install one of: symfony/console[v2.8.11, v4.0.1].
    - Can only install one of: symfony/console[v2.8.12, v4.0.1].
    - Can only install one of: symfony/console[v2.8.13, v4.0.1].
    - Can only install one of: symfony/console[v2.8.14, v4.0.1].
    - Can only install one of: symfony/console[v2.8.15, v4.0.1].
    - Can only install one of: symfony/console[v2.8.16, v4.0.1].
    - Can only install one of: symfony/console[v2.8.17, v4.0.1].
    - Can only install one of: symfony/console[v2.8.18, v4.0.1].
    - Can only install one of: symfony/console[v2.8.19, v4.0.1].
    - Can only install one of: symfony/console[v2.8.2, v4.0.1].
    - Can only install one of: symfony/console[v2.8.20, v4.0.1].
    - Can only install one of: symfony/console[v2.8.21, v4.0.1].
    - Can only install one of: symfony/console[v2.8.22, v4.0.1].
    - Can only install one of: symfony/console[v2.8.23, v4.0.1].
    - Can only install one of: symfony/console[v2.8.24, v4.0.1].
    - Can only install one of: symfony/console[v2.8.25, v4.0.1].
    - Can only install one of: symfony/console[v2.8.26, v4.0.1].
    - Can only install one of: symfony/console[v2.8.27, v4.0.1].
    - Can only install one of: symfony/console[v2.8.28, v4.0.1].
    - Can only install one of: symfony/console[v2.8.29, v4.0.1].
    - Can only install one of: symfony/console[v2.8.3, v4.0.1].
    - Can only install one of: symfony/console[v2.8.30, v4.0.1].
    - Can only install one of: symfony/console[v2.8.31, v4.0.1].
    - Can only install one of: symfony/console[v2.8.32, v4.0.1].
    - Can only install one of: symfony/console[v2.8.4, v4.0.1].
    - Can only install one of: symfony/console[v2.8.5, v4.0.1].
    - Can only install one of: symfony/console[v2.8.6, v4.0.1].
    - Can only install one of: symfony/console[v2.8.7, v4.0.1].
    - Can only install one of: symfony/console[v2.8.8, v4.0.1].
    - Can only install one of: symfony/console[v2.8.9, v4.0.1].
    - Installation request for symfony/console (locked at v4.0.1) -> satisfiable by symfony/console[v4.0.1].

**Comment by fspoettel** [comment]
@ibdf Do you happen to use `Laravel Valet`? This happens because a dep. of `laravel/valet` depends on `symfony/console: ~3.0|~4.0` and `statamic/cli` depends on  `symfony/console: ~2.3|~3.0`. If you install Laravel Valet first, there is a conflict in major versions and the install fails.

I'm not very familiar with PHP tooling, but if you install both packages together or `statamic/cli` first, the cli installs successfully.

@jasonvarga @jackmcdade you might want to bump the `console` dependency so that this does not happen for users just getting started with Statamic since you recommend to install `Valet` in the docs before installing the `cli` which will lead to users getting this error.  Not everyone knows the ins-and-outs of package managers, much less composer.

**Comment by ibdf** [comment]
Yes I have valet. I was planning to use it with statamic. I will see if I can solve the conflict.

**Comment by fspoettel** [comment]
@ibdf Try run 
``` bash
valet uninstall
composer global remove laravel/valet
composer global require statamic/cli
composer global require laravel/valet
valet install
```
\

**Comment by ibdf** [comment]
That worked! No issues this time around, and I was able to start valet and open the default statamic install. Thanks!

**Comment by JonathanCaldwell** [comment]
Thank you! This worked for me, too. I had the exact same problem getting started with Statamic.

**Comment by lumpysimon** [comment]
@fspoettel I was getting the same errors as @ibdf so I've followed your instructions to uninstall valet and remove laravel/valet, but I still can't install Statamic and now I also cannot reinstall Valet either!

Installing Statamic fails with errors about symfony/console, and installing Valet fails with errors about symfony/process

Do you know how I can resolve this? (I know almost nothing about Composer)

**Comment by lumpysimon** [comment]
I've sorted it by manually deleting all my composer files and starting again, installing Statamic first, then Valet

**Comment by fspoettel** [comment]
@lumpysimon glad you sorted it out. the important thing is to install statamic first to prevent the major version conflict between the two project. sort of a bummer that this is still not fixed, I'll try to get a PR ready :)

**Comment by SherG** [comment]
@lumpysimon  - Thanks for the tip. Had to do the same. Even simply removing the Symfony + Laravel folders from the .Composer folder didn't work.

**Comment by connor11528** [comment]
I am getting this error also. I don't even think I have valet installed. What is the best workaround this issue in order to install statamic?

```
$ valet
zsh: command not found: valet
$ composer --version
Composer version 1.6.3 2018-01-31 16:28:17
$ composer global require statamic/cli
Changed current directory to /Users/connor11528/.composer
Using version ^1.0 for statamic/cli
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for statamic/cli ^1.0 -> satisfiable by statamic/cli[1.0].
    - Conclusion: remove symfony/console v4.0.3
    - Conclusion: don't install symfony/console v4.0.3
    - statamic/cli 1.0 requires symfony/console ~2.3|~3.0 -> satisfiable by symfony/console[v2.3.0, v2.3.1, v2.3.10, v2.3.11,
```
