### ISSUE TITLE
Guzzlehttp issue on install

### ISSUE THREAD

**Issue by eheiser** [statamic/cli#22]
Getting the following error when trying to install:

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for statamic/cli ^2.0 -> satisfiable by statamic/cli[2.0.0].
    - Conclusion: remove guzzlehttp/guzzle 4.2.3
    - Conclusion: don't install guzzlehttp/guzzle 4.2.3
    - statamic/cli 2.0.0 requires guzzlehttp/guzzle ^6.5.5|^7.0.1 -> satisfiable by guzzlehttp/guzzle[6.5.5, 7.0.1, 7.1.0, 7.1.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 4.2.3].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 4.2.3].
    - Can only install one of: guzzlehttp/guzzle[7.1.0, 4.2.3].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 4.2.3].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 4.2.3].
    - Installation request for guzzlehttp/guzzle (locked at 4.2.3) -> satisfiable by guzzlehttp/guzzle[4.2.3].

Installation failed, reverting ./composer.json to its original content.
```

Any suggestions?

**Comment by jasonvarga** [comment]
Looks like you have an older version of Guzzle installed.

Run `composer global why guzzlehttp/guzzle` to see what's requiring it.

You probably don't _need_ such an older version.
You may be able to just remove it with `composer global remove guzzlehttp/guzzle`

**Comment by eheiser** [comment]
Cheers Jason, had to remove a few other packages but it's installed now. Thanks for the quick assist!

**Comment by dimitrioskarvounaris** [comment]
For anyone encountering this issue, you may need to update the laravel installer:
``` composer global require laravel/installer ```

This should generally fix it.

**Comment by rabol** [comment]
I have the reverse issue, my global Guzzle version is 7.4, but the statamic cli doe not support guzzle 7.4
