### ISSUE TITLE
Install fails when attempting to create a new site

### ISSUE THREAD

**Issue by MichaelArestad** [statamic/cli#27]
I select the starter kit and then I get this message:

![image](https://user-images.githubusercontent.com/1123119/101220842-adb59780-3643-11eb-90e8-01985eedaed2.png)

I suspect it's related to PHP 8, but I don't know how to find out for sure. I'm new to Statamic so forgive me if I'm missing something. Thank you for your help.

**Details:**
* macOS 11.01
* PHP 8.0.0
* Brew 2.6.0
* Composer 2.0.8
* Valet 2.13.15
* Statamic CLI Tool 2.0.0

**Comment by robdekort** [comment]
Statamic isn't yet compatible with PHP 8 so that could very well explain any issues you're facing. They're working on it though. Have you tried with 7.*?

**Comment by MichaelArestad** [comment]
I downgraded to 7.4 and it's working. Thank you.

**Comment by robdekort** [comment]
Awesome! Have fun!

**Comment by robdekort** [comment]
@jesseleite You can close this issue.
