### ISSUE TITLE
`stamatiс new` does not works on Windows 10

### ISSUE THREAD

**Issue by AlexRadch** [statamic/cli#3]
`statamic new my-site` command return next errors on Windows 10
```
Notice: Undefined index: HOME in C:\Users\rav1\AppData\Roaming\Composer\vendor\statamic\cli\statamic on line 14
Checking for the latest version...
In CurlFactory.php line 187:

  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)


new [--force-download] [--] <name>
```

**Comment by bdahlinger** [comment]
I can verify that this occurred on my Windows 10 system as well.

**Comment by jackmcdade** [comment]
You'll need to setup curl on Windows. Pretty common thing, not Statamic specific :) https://stackoverflow.com/questions/9507353/how-do-i-install-set-up-and-use-curl-on-windows
