### ISSUE TITLE
Can't generate new site via CLI due to symfony console version

### ISSUE THREAD

**Issue by fitzage** [statamic/cli#32]
This really appears to be a laravel issue with Symfony Console 5.3.x, so I'm not sure there's anything you can do. Reporting this issue primarily for others looking for the solution.

When attempting to create a new site using the CLI, I got an error "The no-ansi option does not exist."

Based on [this answer on stackoverflow](https://stackoverflow.com/questions/67774180/the-no-ansi-option-does-not-exist), I downgraded the composer Symfony Console module globally with `composer global require symfony/console:5.2.x` and then `composer global update`, although the last step seemed unnecessary.

After this fix, running the `statamic new <site-name>` command again worked as expected.

**Comment by jasonvarga** [comment]
I believe this will be fixed in the next release of symfony/console.

https://github.com/symfony/symfony/pull/41535
