### ISSUE TITLE
Problem installing Statamic PEAK starter kit

### ISSUE THREAD

**Issue by danielreales7** [statamic/cli#51]
![image](https://user-images.githubusercontent.com/5383214/175039905-751a77e6-3f50-4223-b6bb-f8e5426148a1.png)

When I try to execute this command: statamic new 360-supplier studio1902/statamic-peak everything seems fine except at the end. I get this error.

I'm working on Windows with the Statamic CLI. Anyone on the Statamic Discord encountered this error?

Thank you so much for your help!

**Comment by robdekort** [comment]
The issue was using php7.4. I guess this issue can be closed. Right @danielreales7?
