### ISSUE TITLE
Issue getting this to install

### ISSUE THREAD

**Issue by asha23** [statamic/cli#53]
Hi. Having a small issue getting this installed.

Ran the command

` composer global require statamic/cli`

The following information appears in the terminal, but the download never starts

```
Changed current directory to /Users/******/.composer
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^2.4 for statamic/cli
./composer.json has been updated
Running composer update statamic/cli
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading statamic/cli (2.4.2)
```
It just hangs here doing nothing - I've let it run for 20 minutes... Nothing happens at all.

**Comment by jasonvarga** [comment]
Did you only try it once? What if you cancel and try again?

**Comment by asha23** [comment]
I've tried it a number of times now. Deleted the lock file, restarted my machine. It just hangs for some reason.

**Comment by jasonvarga** [comment]
Can you globally require some other package?

**Comment by asha23** [comment]
Good point. Just tried

` composer global require laravel/installer`

And it now hangs on both statamic and laravel...

```
Changed current directory to /Users/********/.composer
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^4.2 for laravel/installer
./composer.json has been updated
Running composer update laravel/installer
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading laravel/installer (v4.2.10 => v4.2.15)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 1 update, 0 removals
  - Downloading laravel/installer (v4.2.15)
  - Downloading statamic/cli (2.4.2)
 0/2 [>---------------------------]   0%
```

User error I guess.. Maybe my composer installation is broken somehow.

**Comment by asha23** [comment]
Did that, and removed composer.lock as well.

It downloads some things I think. It's now hanging on  `- Downloading laravel/valet (v3.1.9)`

**Comment by asha23** [comment]
In the top bar of the terminal it's flickering between `php and git usr/local/bin/composer global require laravel/installer`

**Comment by jasonvarga** [comment]
At this point I'd say it's not a Statamic issue so you should open up one on the composer/composer repo.

**Comment by asha23** [comment]
Yeah. looks like it might be an issue on my end.  Thanks for your help
