### ISSUE TITLE
Can't install Starter Kit after transferring 'organisation'

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/cli#54]
Hey!

I just transferred my addons & starter kits from the 'doublethreedigital' GH org to my profile 'duncanmcclean'. I've left the namespace and package vendors as the 'doublethreedigital' name (for now at least).

However, now if I try to install a starter kit it won't install with either the new or old names.

Old: https://github.com/doublethreedigital/sc-starter-kit
New: https://github.com/duncanmcclean/sc-starter-kit

I've tried:

statamic new your-new-site-name doublethreedigital/sc-starter-kit
statamic new your-new-site-name duncanmcclean/sc-starter-kit

Any help would be appreciated - not sure if I've missed something or whether it's a bug in the CLI/Core.

**Comment by jasonvarga** [comment]
You haven't updated your composer.json

https://github.com/duncanmcclean/sc-starter-kit/blob/dd08104ab17034026b61caa3f3a470bebf215ec4/composer.json#L2

**Comment by duncanmcclean** [comment]
Ah, that did it! I presumed I wouldn't have to do it since I've kept it the same on my addons.

**Comment by jasonvarga** [comment]
That's because your addons are real composer packages registered on packagist. You can move them anywhere you want.

The starter kit isn't on packagist. We just look in the github repo for a corresponding package. In your case, it didn't match.
