### ISSUE TITLE
Fatal error: Uncaught TypeError: Unsupported operand types: CurlHandle / int in /Users/macpro...

### ISSUE THREAD

**Issue by mware** [statamic/cli#64]
Cannot create a new site with the CLI. 
Running Composer 2.5.5
Statamic CLI 1.0.3
Mac OS Sonoma 14.0

Running `statamic new whatever` throws an error:
```Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/macpro/.composer/vendor/symfony/console/Helper/HelperSet.php on line 104
Checking for the latest version... [✔] 2.11.22
Downloading...
Press Ctrl+C to cancel.

Fatal error: Uncaught TypeError: Unsupported operand types: CurlHandle / int in /Users/macpro/.composer/vendor/statamic/cli/src/Downloader.php:81
```

There might be user error involved or something that needs to be configured on my end? 
Thanks

**Comment by jasonvarga** [comment]
Your version of cli is super old.

Try running `composer global require statamic/cli` to update.

**Comment by mware** [comment]
Thank you @jasonvarga. Ran it, still stuck on 1.0.3.
```Nothing to install, update or remove```
I think the issue is more on my end. We can close this.

**Comment by mware** [comment]
```no matches found: statamic/cli:^3```

**Comment by jasonvarga** [comment]
`composer -V` ?

**Comment by mware** [comment]
```Composer version 2.5.5```

**Comment by jasonvarga** [comment]
Try `composer self-update` and then `composer global require statamic/cli:^3` again. Paste the entire output.

**Comment by mware** [comment]
Here's what I get in return
```macpro@MacBook-Pro-2 ~ % composer self-update
Upgrading to version 2.6.5 (stable channel).
   
Use composer self-update --rollback to return to version 2.5.5
macpro@MacBook-Pro-2 ~ % composer global require statamic/cli:^3
zsh: no matches found: statamic/cli:^3
```

**Comment by robdekort** [comment]
What about `composer global update statamic/cli`?

**Comment by jasonvarga** [comment]
Ok 😄 How about this:

```
composer global require "statamic/cli ^3.0"
```

**Comment by jasonvarga** [comment]
@robdekort If he has v1 in his composer.json file, an `update` isn't going to make the major jump to 3.

**Comment by robdekort** [comment]
Ah got it. I'll see myself out.

**Comment by mware** [comment]
Can I edit that file directly? Currently:
```
{
    "require": {
        "squizlabs/php_codesniffer": "*",
        "statamic/cli": "^1.0"
    }
}
```

**Comment by jasonvarga** [comment]
Yep, change that to `^3.0` then run `composer global update`.

**Comment by mware** [comment]
Success! The CLI tool now works as expected. Thank you so much for patience and sticking with this one. -Michael
