### ISSUE TITLE
Unusable when statamic.com is experiencing an outage

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cli#67]
Apparently if there's an issue with the outpost, this package doesn't work. I didn't experience it myself, I just heard it from someone else. But I'd guess it's when validating starter kit licenses.

**Comment by selastingeorge** [comment]
Hi are you able to fix this, I'm experiencing a similar issue when i try to create a statamic project with starter kit.

![image](https://github.com/statamic/cli/assets/72641365/d1d50ec5-1711-4889-92f3-7ca26e1f5d5a)

### **More Info**
Statmic CLI version : v3.0.1
PHP Version : 8.3.0

**Comment by selastingeorge** [comment]
Finally i was able to fix this issue by adding this to my php.ini file:
`curl.cainfo = "C:\wamp64\bin\php\php8.3.0\cacert.pem"`

I was able to get the cacert.pem file from here: [CA certificates extracted from Mozilla](https://curl.se/docs/caextract.html)

**Comment by duncanmcclean** [comment]
@selastingeorge That's a pretty common issue when using Windows and is unrelated to this. See #3.

**Comment by jasonvarga** [comment]
Maybe we just update the exception to say "Please try again later." 🤷
