### ISSUE TITLE
Weird issues trying to get the CLI to work on Ubuntu

### ISSUE THREAD

**Issue by danielrosehill** [statamic/cli#73]
I'm sure something I'm doing wrong but thought I'd open this issue just in case it's not just me.

Added Statamic as a Bash pass, installed and reinstalled Compose, but still can't get the command to recognise on the terminal for some reason.

![image](https://github.com/statamic/cli/assets/40233203/00f206e5-0206-4dcb-9879-28d5df02b1ec)

And `.bashrc`:

![image](https://github.com/statamic/cli/assets/40233203/6dea93b5-6469-4722-8132-3df94f9ea59a)

OS = Ubuntu LTS

**Comment by jackmcdade** [comment]
Did you reload your bash session?

**Comment by wesort** [comment]
I just experienced this too, but fixed it.

As per the [{s} troubleshooting tip](https://statamic.dev/troubleshooting/command-not-found-statamic), but with this instead ([via SO](https://stackoverflow.com/a/27915343/1515623)) in the `~/.bashrc`:
`export PATH="~/.config/composer/vendor/bin:$PATH"`

This has worked for me, but I have no idea if this is better for that troubleshooting page.

FWIW, this is my context: Digitalocean Droplet provisioned yesterday with Laravel Forge `Ubuntu 22.04.4`. I'll file this with Forge, but feels like this should be part of standard Forge provisioning?

**Comment by danielrosehill** [comment]
> I just experienced this too, but fixed it.
> 
> As per the [{s} troubleshooting tip](https://statamic.dev/troubleshooting/command-not-found-statamic), but with this instead ([via SO](https://stackoverflow.com/a/27915343/1515623)) in the `~/.bashrc`: `export PATH=~/.config/composer/vendor/bin:$PATH`
> 
> This has worked for me, but I have no idea if this is better for that troubleshooting page.
> 
> FWIW, this is my context: Digitalocean Droplet provisioned yesterday with Laravel Forge `Ubuntu 22.04.4`. I'll file this with Forge, but feels like this should be part of standard Forge provisioning?

Thanks, Ben. Worked for me too although the next command is failing. But hey ... the Statamic CLI can run on Linux at least in theory!

**Comment by duncanmcclean** [comment]
I've updated the docs to account for when the Composer path might be different: https://github.com/statamic/docs/commit/8fbdc61f4821679c43f3cca097fc3611882b9e29
