### ISSUE TITLE
Path issues in CLI on Ubuntu Linux

### ISSUE THREAD

**Issue by danielrosehill** [statamic/cli#76]
Thanks to the fix that @wesort posted I was able to get the Statamic CLI at least installed on Ubuntu Linux.

![statamiccli2](https://github.com/statamic/cli/assets/40233203/d6ef375f-9fde-464b-b204-85992043324d)

However when attempting to follow the documentation, the default command to start a new project (`statamic new $project_name`) immediately throws up a PHP error:

![statamic cli](https://github.com/statamic/cli/assets/40233203/8d1f0fbb-7959-4d68-b538-01d703643b9a)

Looking at the path structure, specifically the backslashes, I'm wondering if perhaps this is OS specific

**Comment by duncanmcclean** [comment]
Do you have the [Multibyte String](https://www.php.net/manual/en/mbstring.installation.php) PHP extension installed?
